backup:
  hostname: backups 
  image: indiehosters/backups
  environment:
    - PASSPHRASE
    - FULL_FREQUENCY=7D
    - INC_FREQUENCY=14400
    - PROTOCOL=sftp
    - BACKUP_DESTINATION
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./conf/root:/root
    - /data/domains:/domains
