backup:
  hostname: backups 
  image: indiehosters/backups
  environment:
    - PASSPHRASE
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./conf/root:/root
    - /data/backups/local:/backups
    - /data/domains:/domains
